- name: This is a test...
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: "/var/lib/awx/venv/awx/bin/python"
  tasks:
  - name: Test
    shell: touch /tmp/THIS_IS_MY_TEST
  - name: Test more
    shell: ls -l /
    register: output
  - name: Show output
    debug: msg={{ output }}
  - name: Test more
    shell: hostname
    register: output2
  - name: Show output2
    debug: msg={{ output2 }}
